name: CI

permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl shellcheck shfmt
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install black ruff || true
        
    - name: Lint shell scripts
      run: |
        # Run shellcheck on all shell scripts
        find . -name "*.sh" -type f -exec shellcheck -x {} +
        
    - name: Format check
      run: |
        # Check shell script formatting
        shfmt -d -i 2 -ci *.sh core/*.sh tests/*.sh || true
        # Check Python formatting if files exist
        if find . -name "*.py" | grep -q .; then
          black --check . || true
          ruff check . || true
        fi
        
    - name: Run tests
      run: |
        make test
        
    - name: Test syntax
      run: |
        # Verify all shell scripts have valid syntax
        bash -n camsniff.sh
        for script in core/*.sh tests/*.sh; do
          if [ -f "$script" ]; then
            bash -n "$script"
          fi
        done